[build]
  command = '''
    ruby -v
    bundle env

    rm -rf .bundle/ .jekyll-cache/ vendor/bundle/ && \
    bundle install --path vendor/bundle && \
    bundle clean --force && \
    bundle exec jekyll contentful && \
    bundle exec jekyll build
  '''